# Generated by Django 2.2.2 on 2019-06-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='lastupdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
