# Generated by Django 2.2.2 on 2019-06-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190620_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='currenttoken',
        ),
    ]
