# Generated by Django 2.2.2 on 2019-06-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190622_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Driver'),
        ),
    ]
