# Generated by Django 2.2.2 on 2019-06-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190622_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driverid',
            field=models.IntegerField(unique=True),
        ),
    ]
